import { ProductModel } from "src/app/core/Models/Transactions/product-model";
import { OrderDetailSubItemModel } from "./order-detail-sub-item-model";
import { OrderDetailNoteModel } from "./order-detail-note-model";
import { OrderDetailInsuranceModel } from "../order/order-detail-insurance-model";
import { OrderDetailPromoModel } from "./order-detail-promo-model";
import { OrderDetailTaxModel } from "../order/OrderDetailTaxModel";
import { OrderDetailCancellationModel } from "../order/OrderDetailsCancellationModel";
import { Guid } from "guid-typescript";

export class OrderDetailModel {
  public DocumentId: string;
  public Id: number;
  public DocumentSerial: string;
  public ProductId: number;
  public ProductDocumentId: string;
  public ProductPrice: number;
  public ProductQuantity: number;
  public OriginalProductQuantity: number;
  public ReturnedProductQuantity: number;
  public Printed: boolean;
  public ProductDone: boolean;
  public KitchenDoneDate?: Date;
  public Barcode: string;
  public StationId: number;
  public ProductFinalPrice: number;
  public VolumeId: number;
  public VolumeDocumentId: string;
  public VolumeFerpCode: string;
  public TaxName: string;
  public TaxAmount: number;
  public TaxPercentage: number;
  public ShowVat: boolean;
  public ShowDiscount: boolean;
  public SizeId: number;
  public ParentOrderDetailId: number;
  public IsPromo: boolean;
  public IsParentPromo: boolean;
  public TaxId: number;
  public TaxDocumentId: string;
  public OrderId: string;
  public TransferdOrderId: string;
  public DiscountPercentage: number;
  public DiscountAmount: number;
  // public IsSplitted: boolean;
  public RealPrice: number;
  public OrderDiscountValue: number;
  public OrderDiscountValueToShow: number;
  public SubItemDiscountValue: number;
  public SubItemDiscountAmount: number;
  public ServiceChargeValue: number;
  public ProductName: string;
  public ProductIndex: number;
  public ProductVolumName: string;
  public ShowSideDishes: boolean;
  public ShowNotes: boolean;
  public SideDishesValue: number;
  public SideDishNetPrice: number;
  public SideDishTaxAmount: number;
  public Updatesidedischescheck: boolean;
  public ShowInsurance: boolean;
  public InsuranceValue: number;
  public ShowPromo: boolean;
  public FreeQuantity: number;
  public PromoProductName: string;
  public Total: number;
  public IsDeleted: boolean;
  public IsCancelled: boolean;
  public IsCancelledFront: boolean;
  public IsSync: boolean;
  public ProductGroupId: number;
  public ProductGroupDocumentId: string;
  public ProductGroupName: string;
  public Product: ProductModel;
  public AmountRest: number;
  public EditedPrice: number;
  public OrderDetailSubItems: OrderDetailSubItemModel[];
  public OrderDetailNotes: OrderDetailNoteModel[];
  public OrderDetailInsurances: OrderDetailInsuranceModel[];
  public OrderDetailPromo: OrderDetailPromoModel[];
  public OrderDetailTaxes: OrderDetailTaxModel[];
  public OrderDetailCancellations: OrderDetailCancellationModel[];
  public Selected: boolean;
  public EditingSelected: boolean;
  public QntyToSplit: number;
  public checkedSplit: boolean;
  public ShowEditIconPrice: boolean;
  public NewlyInserted: boolean;
  public IsTransferd: boolean;
  public FirePrint: boolean;
  public TotalSubItemDisountAmount:number = 0;
  public TaxDifferenceValue:number = 0;
  public StartTime: string;
  public EndTime: string;
  public TotalTime: string;
  public QuantityChangedTimes:number;
  UUID:string = Guid.create().toString();
}
