
export class OrderTypeModel {
  public DocumentId: string;
  public Id: number;
  public Name: string;
  public ForeignName: string;
  public FerpCode?: string;
  public Discount: number;
  public IsStopped: boolean;
  public DiscountType: number;
  public Value: number;
  public IsDefault: boolean;
  public ForStaff: boolean;
  public IsTaxesWillBeCalculated: boolean;
  public IsDeliveryIncludedWtithSubtotal: boolean;
  public SelectWaiterInOrder: boolean;
  public IsHosting: boolean;
  public NoteIsRequired: boolean;
  public WillBeUsedForMobileApp: boolean;
  public CompanyId: number;
  public IsDeleted: boolean;
  public IsSync: boolean;
  public Taxes: any[];
  public OrderTypeId: string;
  public PricingClassDocumentId: string;
  public PricingClassId: number;
  public OrderTypeDocumentId: string;
  public PrintReportForOrderNumber: boolean;
  public NotAllowReturnOrder: boolean;
  public IsHasDiscount: boolean;
  public DiscountAccountId: number;
  public PaymentByAnotherUser: boolean;
  public OrderPayTypeDocumentId: string;
  public OrderPayTypeId: number;
  public MustHavePersons: boolean;
  public UseCard: boolean;
  public MustHaveCustomer: boolean;
  public MandatoryToSelectThisType: boolean;
  public IsPromo?: boolean;
  public VerifiedOrderByPinBeforeSave?: boolean;
  public DirectPayment : boolean;
  // public DoesNotUseTax:boolean;
}
