export class SettingModel {
  public DocumentId: string;
  public Id: number;
  public OrderNumberGenerationPeriod: number;
  public OrderNumberGenerationType: number;
  public FinancialSystem: number;
  public ShowEndShiftReportpasedOnPayType: boolean;
  public CalculateTaxBeforeDiscount: boolean;
  public IsServiceFromRealPrice: boolean;
  public IsServiceFromTotalWithVat: boolean;
  public CalculateTaxBeforeDiscountNum: number;
  public IsServiceFromRealPriceNum: number;
  public PrintReceiptOnce: boolean; //this means print receipt only once  CustomerProductNamePrintingOption
  public PrinterName: string;
  public PreventChangeCashierInReturnOrder: boolean;
  public UseDailyStocks: boolean;
  public UseStocksAndPurchase :boolean;
  public PushOrdersAutomaticToAuthority: boolean;
  public UseMinimumCharge: boolean;
  public ShowBothNameAndForeignName: boolean;
  public UseMyPoints: boolean;
  public PrintReceiptInClosing: boolean;
  public PreventClosingWithoutFullPayment: boolean;
  public HideCloseOrderWithDineIn: boolean;
  public ShowProductsAvalQty: boolean;
  public AllowUsingProductsWithNoAvalQty: boolean;
  public PriceIncludesTax: boolean;
  public ShowCustomerInfoForKitchen: boolean;
  public KitchenProductNamePrintingOption: number;
  public CustomerProductNamePrintingOption: number;
  public OrdersShowProductNameOption: number;
  public MustAssignWaiters: boolean;
  public MustAssignCaptain: boolean;
  public AllowEnterReturnOrderDateAsOrderDate: boolean;
  public UsedApprovedScreen: boolean;
  public ReportFileForBundledOrder: string;
  public KOTReportFileInCashierPrinter: string;
  public ReportFileForCustomerReceipt: string;
  public DeliveryFromTime: string;
  public DeliveryToTime: string;
  public DeliveryMinSubTotal: number;
  public DeliveryMaxSubTotal: number;
  public IsDeliveryFreeForAll: boolean;
  public IsDeliveryFreeForBigOrders: boolean;
  public BigOrdersSubTotal: number;
  public IsDeliveryFixed: boolean;
  public FixedDeliveryPrice: number;
  public SetOrderPaidAutomatically: boolean;
  public AddDeliveryPriceToReciept: boolean;
  public SalesReceiptType: number;
  public DistanceToGetRelatedBranches: number;
  public ShowSpecialReport: boolean;
  public PercentOfSpecialReport: number;
  public UseAccounting: boolean;
  public Round: number;
  public UseHumanResource: boolean;
  public PrintNotLinkedProductsinCachier: boolean;
  public HideZerosProducts: boolean;
  public InsertReceiptTransferAuto: boolean;
  public PrintbytheAPI: boolean;
  public PrintOrdersByOrderTypes: boolean;
  public SetReturnOrderDate: boolean;
  public RTOPrinterId: string;
  public PrintCustomerReceiptAfterSendDeliveryOrder: boolean;
  public HiddenReportHeader: boolean;
  public CompanyId: number;
  public IsDeleted: boolean;
  public IsSync: boolean;
  public IsMain: boolean;
  public UseTax: boolean;
  public NamesOfProductsBasedOnMainUserLang: boolean;
  public FirstHour: string;
  public IsStockAdjustment: boolean;
  public Paymentofnoncashdeliveryorders: boolean;
  public ShowQrCode: boolean;
  public EncryptQrCode: boolean;
  public OpenSideDishesPopUpAfterSelectProduct: boolean;
  public CustomerReceiptReportFile: string;
  public CustomerReceiptReportLanguage1: number;
  public CustomerReceiptReportLanguage2: number;
  public ReportDirection: number;
  public KOTFile: string;
  public KOTBoundelFile: string;
  public CopyInCashierPrinterFile: string;
  public ReportPath: string;
  public DirectionList: any;
  public LanguageList: any;
  public CalculateTaxBeforeDiscountList: any;
  public IsServiceFromRealPriceList: any;
  public KOTSeparateList: any;
  public KOTModelList: any;
  public OrderModelList: any;
  public ReportFile: string;
  public KOTSeparate: number;
  public ApplyTaxOnDeliveryPrice: boolean;
  public TaxDocumentId: string;
  public CountryType: number;
  public SystemMainLanguage: number;
  public CheckOrderCount: boolean;
  public UseTaxPrinter: boolean;
  public TaxPrinterReportName: string;
  public TaxPrinterName: string;
  public Reports: any;
  public Printers: any;
  public PaidDeliveryOrderWhenAssignAddExitToDriver: boolean;
  public UseDailyStock: boolean;
  // public DailyStockIsRepeatedAutomatically: boolean;
  public ShowRemainingCustomerRequestsToBeDeliveredHowManyDays: number;
  public PaymentButtonDirectly: boolean;

  public ProductWidth: number;
  public DetailCartWidth: number = 33.33;
  public ProductCartWidth: number = 66.67;
  public ProductHeight: number;
  public DontUsePageinationInOrderScreen: boolean;
  public ProductBGColor: string;
  public ProductNameFontSize: number;
  // Turkey Payments
  //   public IsUsingIngenico:boolean;
  //   public IngenicoPort:string;
  //   public IngenicoPayTypeDocumentId:string;
  //   public IsUsingInfoteks:boolean;
  //   public InfoteksPort:string;
  //   public InfoteksPayTypeDocumentId:string;
  public ClickProductPlusQuantity: boolean;
  public PrintSideDishesInLinkedPrinters: boolean;
  public PrintComboContentsInLinkedPrinters: boolean;
  public PrintReturnOrderInKithcen: boolean;
  public IsCloud: boolean;
  public FirstLogIn: boolean;

  public CanNotEditOrderByAnother: boolean;
  public StopDealingWithShiftes: boolean;
  public PostingOrders: number;
  public PostingOrdersList: any[];

  public DealingWithStockAs: StockType;
  public DealingWithStocList: any[];

  public RoundingMethod: number;
  public RoundingLevel: number;
  public UseAutoReceivingTransfer: boolean;
  public ChangeOrderTypeAfterSave: boolean;
  public AutoReceivingTransferMinutes: number;
  public SenderEmail: string;
  public ReceivedEamil: string;
  public IncreptedCode: string;
  public UseEmail: boolean;
  public IsUsingCustomerPriceDisplay: boolean;
  public COMPort: string;
  public WelcomeMessage: string;
  public CustomerPriceDisplayCurrency: string;
  public EndMessage: string;
  public UsingDrawer: boolean;
  public DrawerCOMPort: string;
  public DrawerType: number;
  public AddFingerPrintWhenLoginOrOutTheSystem: boolean;
  public CloseCashAfterClosingAllopenOrders: boolean;
  public OrderReportModel: number;
  public KOTReportModel: number;
  public NotClosedOrderCheck: boolean;
  public CurrentUserName: string;
  public MustSelectDriverBeforeSave: boolean;
  public PullAllTablesFromPOS: boolean;
  public CustomerScreenModel: number;
  public PullSettings: boolean;
  public PullPromos: boolean;
  public PullWorkTimes: boolean;
  public connSetting: any = {};
  public FerpUrl: string;
  public PushUrl: string;
  public PushToServerList: any;
  public PullFromServerList: any;
  public Pull: number;
  public Push: number;
  public PushMintes: number;
  public PullMintes: number;
  public ShowVolumeAsProduct : boolean;
  public IncludeExtraExpensesAndCancelOrdersInEndOfDayReport : boolean;
  public UseMyCoupons : boolean;
  public MustSelectSideDishMaxQty : boolean; // ForOnlineOrder
  
  public LinkWithHotel :boolean;
  public HotelCustomerDoumentId :string;
  public HotelUrl :string;
  public CountryCode :string;

  public AllowMultiTaxOnPrduct :boolean = false;
  public DeleteOrderAfterSynced :boolean = false;
  public DealingWithWhatsApp :boolean = false;
  public SendWhatsAppOnDeliveryOrders :boolean = false;
  public SendWhatsAppOnAssignToDelivery :boolean = false;
  public SendWhatsAppOnReturnOrder :boolean = false;
  public SendWhatsAppOnEndShift :boolean = false;
  public SendWhatsAppOnCloseDay :boolean = false;
  SendWhatsAppToDriver:boolean = false;
  public AutoHeight :boolean = false;
  public DateFormFirstHour :Date = new Date();
  public PrintSeparateInsuranceReport :boolean = false;
  public PathToWhatsAppEXE :string;
  public PathToTaxPrinter :string;
  public PathToResponseOfTaxPrinter :string;
  public PathToSaudiTaxApi :string
  public HideActualRevenueInEndShiftReport :boolean = false;
  public WhatsAppOnReturnOrderPhone :string | null;
  public WhatsAppOnReturnOrderPhone2 :string | null;
  public WhatsAppOnEndShiftPhone :string | null;
  public WhatsAppOnEndShiftPhone2 :string | null;
  public WhatsAppOnCloseDayPhone :string | null;
  public WhatsAppOnCloseDayPhone2 :string | null;
  public UseKiosk :boolean = false;
  public UseKioskMemberId :boolean = false;
  public UseFirePrint :boolean = false;
  MustSelectSideDishesInOrders:boolean;
  public AddCancelReasonFromOrder :boolean = false;
  public CloseAllIncomingInDayOpened :boolean = false;
  public CanChangeTableNameInOrder :boolean = false;
  public AssignCaptainToOrderTypes :string[] | null;
  public ShowVolumeNameBeforeProductName :boolean = false;
  public VolumeAndProductNameSeparatorCharacter :string[] | null;
  public TimeZone :string | null;
  public IsDeliveryIncludedInRevenueAsPercentage :boolean;
  public DeliveryIncludedPercentage :number;
  public NotSyncOrderToServerIfNotTaxSynced :boolean;
  public DonotShowNotPrintedOrders :boolean;
  public ShowProductCodeWithNameInOrderScreen :boolean;
  public OrderInsuranceHideList :boolean;
  public UsePendingOrders :boolean;
  public AllowAdminAccessPOSTransactons :boolean;
  public DefaultOrderPreparationTimeInMinutes :number;
  public DonotUsePOSInIncomingUser :boolean;
  public CannotUpdateAfterAssignDriver :boolean;
}
enum StockType {
  Stock = 1,
  Kitchen = 2
}
