import { OrderPaymentModel } from "./OrderPaymentModel";
import { OrderDetailModel } from "../Transactions/order-detail-model";
import { OrderMasterTaxModel } from "../Transactions/order-master-tax-model";
import { OrderTypeModel } from "../Transactions/order-type-model";
import { ReturnOrderModel } from "./returnOrderModel";
import { CustomerAddressModel } from "../Transactions/CustomerAddressModel";
import { CustomerModel } from "../Transactions/CustomerModel";
import { DriverModel } from "../Transactions/DriverModel";
import { MyPointModel } from "./MyPoint.Model";

export class OrderModel {
  constructor() {
    this.Customer = new CustomerModel();
    this.Driver = new DriverModel();
    this.CustomerAddress = new CustomerAddressModel();
    this.OrderType = new OrderTypeModel();
    this.OrderMasterTaxes = [];
    this.OrderDetails = [];
    this.ReturnOrders = [];
    this.OrderPayments = [];
    this.OrderInsurance = {};
  }

  public DocumentId: string;
  public ReferenceCode: string;
  public IntegrationSystem: number;
  public IntegrationCustomerId:number |null = null;
  public IntegrationCustomerDocumentId:string |null = null;
  public Id: number;
  public Pin: string;
  public BranchId: number;
  public BranchName: string;
  public Serial: string;
  public OrderTypeId: number;
  public OrderTypeDocumentId: string;
  public OrderTypeName: string;
  public IsCalculated: boolean;
  public IsDeleted: boolean;
  public IsHallPos: boolean;
  public OrderNumber: number;
  public NetTotal: number;
  public Total: number;
  public SubTotal: number;
  public Discount: number;
  public DiscountType: string;
  public OriginalDiscountType: string;
  public CustomerDocumentId: string;
  public CustomerId: number;
  public CustomerName: string;
  public CustomerPhone: string;
  public WaiterId: number;
  public WaiterDocumentId: string;
  public WaiterName: string;
  public CaptainName: string;
  public CaptainId: number;
  public CaptainDocumentId: string;
  public CustomerAddressDocumentId: string;
  public CustomerAddressId: number;
  public ServiceChargeValue: number;
  public ServiceChargePercentage: number;
  public TotalTaxAmount: number;
  public DiscountAmount: number;
  public DetailsDiscount: number;
  public TotalInsuranceAmount: number;
  public NoteId: number;
  public OrderPayTypeId: number;
  public OrderPayTypeDocumentId: string;
  public OrderPayTypeName: string;
  public PayAmount: string;
  public VisaAmount: number;
  public ExtraService: number;
  public DeliveryPrice: number;
  public DeliveryNetPrice: number;
  public IsDeliveryNetPriceHandled: boolean;
  public RemainigAmount: number;
  public DeliveryPersonDeliveryPrice: number;
  public RservationDate: Date;
  public Paid: boolean;
  public DriverPaid: boolean;
  public Date: Date;
  public TableId: string;
  public OrderTable: any;
  public TableName: string;
  public DriverId: number;
  public DriverDocumentId: string;
  public DriverName: string;
  public IsChecked: boolean;
  public EmployeeId: string;
  public EmployeeDocumentId: string;
  public EmployeeName: string;
  public PrintCount: number;
  public CloseDate: Date;
  public Status: number;
  public ClosingUserId: number;
  public ClosingUserName: string;
  public WorkTimeId: number;
  public WorkTimeDocumentId: string;
  public HostName: string;
  public PersonsCount: number;
  public PinUserId: number;
  public Posted: boolean;
  public ReferenceId: number;
  public NoteForOrder: string;
  public ExtraNote1: string;
  public ExtraNote2: string;
  public ExtraNote3: string;
  public IsSync: boolean;
  public IsView: boolean;
  public isAdmin: boolean;
  public IsSplitOrder: boolean;
  public IsDevidOrder: boolean;
  public IsChangeTable: boolean;
  public IsSelected: boolean;
  public Ispayment: boolean;
  public userPermissions: any;
  public CashierName: string;
  public PayName: string;
  public DeliveryAssignTime: Date;
  public DeliveryBackTime: Date;
  public DeliveryExitTime: Date;
  public TotalDeliverPrice: number;
  public DriverPhone: string;
  public class: string;
  public Reservation: boolean;
  public PayedAmountReservation: number;
  public CallCenterBranch: string;
  public IsCallCenter: boolean;
  public Approved: boolean;
  public IsMobileOrder: boolean;
  public CustomerAddress: CustomerAddressModel;
  public settings: any;
  public pointOfSale: any;
  public Customer: CustomerModel;
  public Driver: DriverModel;
  public OrderType: OrderTypeModel;
  public OrderMasterTaxes: OrderMasterTaxModel[];
  public OrderDetails: OrderDetailModel[];
  public ReturnOrders: ReturnOrderModel[];
  public OrderPayments: OrderPaymentModel[];
  public OrderInsurance: any;
  public LanguageOptions: any;
  public OrderInsuranceItems: any;
  public appUserId: number;
  public allUsers: any;
  public RoundingFraction: number;
  public FreePaymentCalculated: boolean;
  public DispalyMode: number;
  public NoPrinting: boolean;
  public DiscountPer: number;
  public DiscountVal: number;
  public CardNumber: string;
  public validationList: any;
  public IsDriver: boolean;
  public HasMinimumCharge: boolean;
  public MinimumChargeValue: number;
  public MinimumChargeNewPerPerson: number;
  public MinimumChargeDifferance: number;
  public Free: boolean;
  public FromTaxScreen: boolean = false;
  public minChargeTaxValue: number;

  public UpdatedNewDetails?: boolean;

  public IsSuspended?: boolean;
  public IsScheduled?: boolean;

  // For scheduled orders
  public IsCustomerOrder?: boolean;
  public ReservationInfo: any = {};
  public IsIntegrationCourier?: boolean;
  public IsSendToKitchen?: boolean;
  public RemoteStatus?: number;
  public UserId?: string;

  public IsCustsomerPromo?: boolean;

  public PointsCountApplied?: number;
  public myPoint:MyPointModel;
  public CouponApplied?: string;
  public PricingClassDocumentId: string;

  public OtelPrimoRoomNo :number;
  public OtelPrimoRoom : any;
  //// new columns 
  
  public ReceivedDate : string | null;
  public ReservationToTime : string | null; 
  public ReservationFromTime : string | null;
  public VerifiedByUserId: number | null;
  public IsTransferd?: boolean;
  public ChannelName: string | null;
  public IsDeliverectOrder: boolean;
  public Tips:number;
  public CancelServices:boolean;
  public SplitName:boolean;
  public FoodPlanDiscountAmount:number;
  // public DoesNotUseTax:boolean;
  // for front olny
  requestStarted:boolean = false;
  paymentErrorFired:boolean = false;
  VisaSameOrderPayTimeCount: number = 0;
  FoodPlanProductFilterd: boolean;
  orderTypeChangedAfterSave: boolean = false;
  FoodPlanData: any;
  IsPreparationTimeFinished:boolean;
}
