import { OrderPayTypeModel } from "../Transactions/order-pay-type-model";
import { OrderModel } from "./orderModel";
import { OrderPaymentModel } from "./OrderPaymentModel";
import { OrderPayTypeDropDownModel } from "./orderPayTypeDropDownModel";
import { ReturnOrderDetailModel } from "./returnOrderDetailModel";
import { DynamicCombo } from "../Transactions/dynamic-combo";
import { OrderMasterTaxModel } from "../Transactions/order-master-tax-model";
import { TaxModel } from "./TaxModel";

export class ReturnOrderModel {
  public DocumentId: string;
  public Id: number;
  public BranchId: number;
  public OrderId: string;
  public IsDeleted: boolean;
  public IsSync: boolean;
  public ReturnDate: Date;
  public CashierId: number;
  public CashierName: string;
  public OrderPayTypeId: number;
  public Count: number;
  public OrderDate: Date;
  public Order: OrderModel;
  public ReturnOrderNumber: number;
  public OrderNumber: number;
  public ReturnReason: string;
  public NetTotal: number = 0;
  public SubTotal: number = 0;
  public ServiceChargeValue: number = 0;
  public TotalTaxAmount: number = 0;
  public DeliveryPrice: number = 0;
  public TotalDiscountAmount: number = 0;
  public CustomerDocumentID: string;
  public OrderPayTypeDropDownModels: OrderPayTypeDropDownModel[];
  public OrderDropDownModels: OrderModel[];
  public POSReturnOrderDetails: ReturnOrderDetailModel[];
  public POSReturnOrderPayments: OrderPaymentModel[];
  public ReturnOrderMasterTaxes: OrderMasterTaxModel[] =[];
  public screenPermission: any;
  public Approved: Boolean;
  public ReturnOrderDateEnum: number;
  public OrderMasterTaxesTotal: number;
  public OrderDetailTaxesTotal: number;
  public MinimumChargeDifferance: number = 0;
  public isServiceChargeReturned: boolean = false;
  public isMinChargeReturned: boolean = false;
  public OrderTypeName: string | null;
  public LanguageOptions: any;
  PinUserId:string;
  IsMultiOrders: boolean = false;
  Taxes:TaxModel[] = [];
}
